/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package analisador;

import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JLabel;
import java.awt.FlowLayout;
import java.awt.Color;

/**
 *
 * @author RODOLFO
 */
public class sobre extends javax.swing.JFrame {

    /**
     * Creates new form sobre
     */
    public sobre() {
    	setBackground(Color.RED);
    	getContentPane().setBackground(Color.RED);
    	setForeground(Color.RED);
    	setTitle("Sobre o CalcSpi");
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBackground(new Color(255, 0, 0));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(Color.WHITE);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setForeground(Color.WHITE);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(Color.WHITE);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setForeground(Color.WHITE);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setForeground(Color.WHITE);
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setForeground(Color.WHITE);
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setForeground(Color.WHITE);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setText("Informa\u00E7\u00F5es do programa");

        jLabel2.setText("CalcSpi");

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel3.setText("Descri\u00E7\u00E3o:");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel5.setText("Autores:");

        jLabel6.setText("Am\u00E1lia Spineli Oliveira");

        jLabel7.setText("Victor Henrique de Freitas Silva");

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel8.setText("Nome do Programa:");
        
        lblCalculadoraComNmeros = new JLabel("Calculadora com n\u00FAmeros naturais e reais com opera\u00E7\u00F5es como: soma, subtra\u00E7\u00E3o, multiplica\u00E7\u00E3o, divis\u00E3o, raiz quadrada, pot\u00EAncia, fatorial, entre outras.");
        lblCalculadoraComNmeros.setForeground(Color.WHITE);
        
        lblNewLabel = new JLabel("O objetivo \u00E9: por meio de comandos definidos pela linguagem, ser\u00E1 poss\u00EDvel realizar as opera\u00E7\u00F5es.");
        lblNewLabel.setForeground(Color.WHITE);
        
        lblAoInvsDo = new JLabel("Ao inv\u00E9s do usu\u00E1rio clicar nos s\u00EDmbolos correspondentes \u00E0 opera\u00E7\u00E3o que deseja fazer, ele vai digitar o comando correspondente, ou seja, o deficiente");
        lblAoInvsDo.setForeground(Color.WHITE);
        
        lblVisualNoTer = new JLabel("visual n\u00E3o ter\u00E1 dificuldades para calcular uma opera\u00E7\u00E3o.");
        lblVisualNoTer.setForeground(Color.WHITE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(20)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2)
        						.addComponent(jLabel3)
        						.addComponent(jLabel8)
        						.addComponent(lblCalculadoraComNmeros)
        						.addComponent(lblNewLabel)
        						.addComponent(lblAoInvsDo)
        						.addComponent(lblVisualNoTer)
        						.addComponent(jLabel5)
        						.addComponent(jLabel6)
        						.addComponent(jLabel7)))
        				.addComponent(jLabel1))
        			.addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addComponent(jLabel1)
        			.addGap(16)
        			.addComponent(jLabel8)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(lblCalculadoraComNmeros)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(lblNewLabel)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblAoInvsDo)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblVisualNoTer)
        			.addGap(43)
        			.addComponent(jLabel5)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel6)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel7)
        			.addGap(25))
        );
        jPanel1.setLayout(jPanel1Layout);
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sobre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new sobre().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private JLabel lblCalculadoraComNmeros;
    private JLabel lblNewLabel;
    private JLabel lblAoInvsDo;
    private JLabel lblVisualNoTer;
    // End of variables declaration//GEN-END:variables

    private void EXIT() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
