
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisador;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int bool = 8;
  public static final int AbParentese = 10;
  public static final int escreva = 3;
  public static final int atribuicao = 24;
  public static final int retorna = 5;
  public static final int DoisPontos = 32;
  public static final int Variavel = 21;
  public static final int break1 = 30;
  public static final int AbChave = 14;
  public static final int QuebraLinha = 7;
  public static final int leia = 4;
  public static final int se = 16;
  public static final int senao = 17;
  public static final int FinalLinha = 2;
  public static final int Fchparentese = 11;
  public static final int EOF = 0;
  public static final int AbColchete = 12;
  public static final int enquanto = 18;
  public static final int para = 19;
  public static final int error = 1;
  public static final int ou = 35;
  public static final int OpRelacional = 22;
  public static final int caractere = 9;
  public static final int FchColchete = 13;
  public static final int switch1 = 31;
  public static final int caso = 20;
  public static final int tipo = 25;
  public static final int virgula = 29;
  public static final int texto = 27;
  public static final int aspas = 33;
  public static final int comentario = 6;
  public static final int erro = 28;
  public static final int e = 34;
  public static final int num = 26;
  public static final int OpMatematica = 23;
  public static final int FchChave = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FinalLinha",
  "escreva",
  "leia",
  "retorna",
  "comentario",
  "QuebraLinha",
  "bool",
  "caractere",
  "AbParentese",
  "Fchparentese",
  "AbColchete",
  "FchColchete",
  "AbChave",
  "FchChave",
  "se",
  "senao",
  "enquanto",
  "para",
  "caso",
  "Variavel",
  "OpRelacional",
  "OpMatematica",
  "atribuicao",
  "tipo",
  "num",
  "texto",
  "erro",
  "virgula",
  "break1",
  "switch1",
  "DoisPontos",
  "aspas",
  "e",
  "ou"
  };
}

